### PR TITLE
Add getAttacks and getDmgs for standard attacks

### LINKED ISSUE #3: implement the !attack command
where BBW uses the correct modifiers and weapons

### PR DESCRIPTION
**Pull request by cattabiani**
- Add small character unit test

Fix #3 

- [x] add throw and attack frontend commands (not tested)
- [x] add tags for wapons
- [x] add `shoot` command for range attacks (since some weapons can be thrown or used melee)
- [x] add `throw` command for throwing attacks
- [x] add possibility to throw with stuff that is not wielded 
- [x] add `swapWeapons` to change main weapon (first in the list of wielded items)
- [x] add `isRanged` do distinguish between ranged and melee attacks
- [x] add `[God]` modifiers for Dominus
- [x] add ammo mechanics

Improvements:
- [x] group together atk and dmg
- [x] make tagging manual with: addTag, removeTag, autoTag
- [x] print possible tags
- [x] save/load new tagging system
- [x] move wearable,wildable, etc into tagging system
- [x] print tags with equipment

### CODE REVIEW

**Review by slithy — CHANGES_REQUESTED** [review]
The test `if weapon.range <= 1` is not sufficient to determine if a weapon is a melee weapon. Daggers, hand axes and clubs can all be used in melee, or thrown. Better to add properties to the weapon class to say what kind of weapon it is, for example:

* isMelee() - e.g. sword, dagger, club, spear, axe, hammer
* isThrowable() - e.g. dagger, club, spear, hand axe, throwing hammer, javelin, stone, dart
* isLauncher() - e.g. bow, sling
* isAmmo() - e.g. arrow, quarrel, sling bullet

Some weapons have more than one of these properties.

Launchers and ammo have to be used in conjunction and you have to add the bonuses of both. For example, someone with Dex 16 shooting with a magic bow +2 and a magic arrow +1 will have total bonuses +2+2+1 = +5.

**Comment by cattabiani** [comment]
@slithy enchanted arrows could be a problem. I already see someone that forgets that is wielding an enchanted arrow, he shoots and loses the arrow, complaining. I would just omit that arrow and let the player add its modifier + drop the arrow if he really wants to use it. Also the idea od automatizing the arrow use is a little double edged; I do not know what arrow a player wants to use. For now I would let them manage the arrows. What do you think?

**Comment by slithy** [comment]
The way I was thinking of handling different kinds of attacks:

* Melee: straightforward, you attack with the weapon(s) you are wielding
* Ranged, thrown: have a "throw" command which selects the weapon: "throw spear", "throw stone", "throw axe", etc.. You don't have to be wielding it. If you say throw without specifying, throw whatever you are wielding (if it is throwable).
* Ranged, launcher. You have to be wielding the launcher (bow, crossbow, sling, etc.) Have a command "shoot"/"fire" (synonyms): "shoot arrow", "shoot bolt", "fire stone", etc. Each launcher can have a default ammo that it can fire, so if you are wielding a bow and say "shoot", you will by default shoot an arrow. But if you want to shoot a special arrow (silver arrow, magic arrow, etc.) then you have to explicitly say "shoot magic arrow".

**Comment by cattabiani** [comment]
@slithy shall I auto-drop the ammos/weapons that are auto-thrown? I am afraid this could generate anger if someone does not remember to re-equip the item. Also it is verbose ofr the player to re-inser the weapon in the inventory. Maybe just the ammos?

**Comment by cattabiani** [comment]
bonus questions:
what tags for a whip?

**Comment by cattabiani** [comment]
I think it is better to add a tagging system than all these is*** functions. It is easily expandable without an explosion in methods

**Comment by slithy** [comment]
Auto-drop for thrown weapons: I would say no, as normally these will be picked up again at the end of the battle. But for ammo, yes.

(An alternative would be to not delete items when they are dropped, but have them go to "ground" where they can be picked up again.)

**Comment by slithy** [comment]
Whip is like a special case of throw: you have to be wielding it and it doesn't leave your hand when "thrown".

**Comment by cattabiani** [comment]
@slithy I did not test the commands with the whole system up, just a few unit tests. We already have standard melee attacks and throws that are 90% of our normal attacks. May you pull this branch next time to test it in game?

**Comment by cattabiani** [comment]
I am trying to modify the tagging system. I added add and remove tags function to fully customize the item. I do not see an easy way to allow this during the !equip command (the syntax is not clear). Can I write something like:

`!equip "Throwing hammer" weapon ev:4 dmg:1d6 range:30 tags: melee, throw`

or something similar? I am not sure how the discord stuff understands this

**Comment by cattabiani** [comment]
@slithy another question: what is an ammo exactly? Because we said it is a weapon (your comment before) but in the code weapons are unique (the count must be 1). 
`raise UniqueItem("Weapons are unique (count must be 1)")` What do you prefer to proceed? Either ammos are not weapons or we remove the limitations on weapons...

**Comment by slithy** [comment]
Ammo do not have the characteristics of weapons, they should be a class on their own. They cannot be wielded, they have no range (it's the launcher that has range, e.g. a shortbow and a longbow have different ranges but they both shoot arrows) and they can't be used independently of the launcher. And yes, arrows are countable.

Ammo should specify what type of launcher it works with. e.g. a sling stone cannot be fired by a bow. Or else the launcher should specify what type of ammo it can use.

Ammo do have damage and can have a bonus to hit which adds to the launcher BtH (e.g. magic arrows).

**Comment by cattabiani** [comment]
@slithy ... and how do you classify rocks, stones and darts? They can be thrown as weapons or used in slings/blowpipes I think. Isn't is simpler to just remove the count limit to weapons? When you add a weapon that has the same name you increase the count. If you add a new weapon with different stats we implement the __eq__ function using the json representation. If they differ we throw an error

Maybe we do not need this level of automation. I have already seen florian complaining that everything is getting to much automation. We can let the player drop the correct ammo. It is not a difficult task where you need to remember stats

**Comment by slithy** [comment]
Removing the count limit of weapons introduces a lot more complexity. Suppose you have two daggers and you "!wield dagger". Now you have to record that one dagger is wielded and the other one is not. What if you want to wield both daggers? Or you have three and want to wield two of them? What if you throw one dagger? If you want to add code to handle all the possible cases then the count limit can be removed.

Treat rocks and stones as ammo. You can't wield these but they can be fired from a sling, or thrown.

Maybe ranged weapons like javelins and darts can also be treated as ammo, they can't be wielded or shot but you can throw them. (Note that "darts" are like mini javelins, they are not the same thing as blowpipe darts).

photo

**Comment by cattabiani** [comment]
this introduces a new level of complexity because throw can use a weapon and an ammo

**Comment by cattabiani** [comment]
and if you want to wield 2 stones?

**Comment by slithy** [comment]
Wielding stones is really a corner case, I would just make stones not wieldable.

I guess anything can be throwable. You could define a throw() method on the base class, do 1d2 damage by default and reduce count of the item by 1 (or drop the item). Then override that for weapons and ammo to use the defined damage instead.

**Review by cattabiani — COMMENTED** [review]
this code is old

**Comment by cattabiani** [comment]
@slithy I think the changes you requested are no more relevant. May you review again? I think we are ready

**Review by slithy — APPROVED** [review]

**Comment by slithy** [comment]
OK, merged to master.

**Pull request merged**
